### ISSUE TITLE
About time step

### ISSUE THREAD

**Issue by StephanieDU** [MatheusMRFM/A3C-LSTM-with-Tensorflow#4]
Thanks for your work. After reading your code, I am confused by the use of frames_stacked, since LSTM can already remember the sequence info among frames, what is the meaning of using 4 frames as input? Looking forward to your reply.

**Comment by MatheusMRFM** [comment]
Hello there! Your comment makes a lot of sense. Basically, I just copied the structure from the [original A3C paper](https://arxiv.org/abs/1602.01783), where it is said that A3C uses a similar network structure as the DQN. Maybe a misunderstood something, but I left the input with the last four frames stacked. However, if I'm not mistaken, I have also tested it with only the last frame as input (when using the LSTM) and it still managed to work fine.

**Comment by StephanieDU** [comment]
Thanks so much for your prompt reply! I have learned a lot from your code. Many thanks.
